authors:
  <qihang>:
    name: Qihang        # Author name
    description: NaN # Author description
    avatar: https://avatars.githubusercontent.com/u/148497514?v=4         # Author avatar
  <jiaming>:
    name: Jiaming        # Author name
    description: NaN # Author description
    avatar: https://avatars.githubusercontent.com/u/148497514?v=4         # Author avatar