site_name: Open Finance Blog

site_url: https://open-finance-tools.github.io/Finance-Blog

repo_url: https://github.com/open-finance-tools/Finance-Blog
repo_name: open-finance-tools/Finance-Blog

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://github.com/open-finance-tools
  tags:
    HTML5: html
    JavaScript: js
    CSS: css

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  

extra_javascript:
  # - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - blog:
      blog_dir: Timeline
      blog_toc: true
      post_dir: "{blog}/blog"
      post_date_format: medium
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      # authors: true
      authors_file: "{blog}/.authors.yml"
      draft: true
      draft_if_future_date: true
  - tags
  - info:
      enabled: false
      enabled_on_serve: true
      archive: false
      archive_stop_on_violation: false
  - offline
  # - offline:
  #     enabled: !ENV [OFFLINE, false]

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
  language: en
  logo: assets/fruit/watermelon.svg
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/git-alt
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
  favicon: assets/fruit/lemon.svg


  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

nav: 
  - Homepage: index.md
  - Basic: 
    - About: Basic/About.md
  - Timeline: 
    - index: Timeline/index.md
